import 'locale_keys.dart';

const Map<String, dynamic> englishLocalization = {
  LocaleKey.stepCounter: "Step Counter",
  LocaleKey.today: "Today",
  LocaleKey.home: "Home",
  LocaleKey.activities: "Activities",
  LocaleKey.goal: "Goal",
  LocaleKey.steps: "steps",
  LocaleKey.kCal: "kCal",
  LocaleKey.km: "Km",
  LocaleKey.min: "min",
  LocaleKey.setDailyGoal: "Set a daily goal!",
  LocaleKey.ourInspiredToBetterThemselves:
      "Our 91% inspired to better themselves.",
  LocaleKey.setNow: "Set Now",
  LocaleKey.healthTracker: "Health Tracker",
  LocaleKey.trendsInsights: "Trends & Insights",
  LocaleKey.navigateYourPath: "Navigate Your Path",
  LocaleKey.weightBMI: "Weight & BMI",
  LocaleKey.cultivateWellnessTrackWeightMeasureHealth:
      "Cultivate Wellness: Track Weight, Measure Health",
  LocaleKey.gpsTracking: "GPS Tracking",
  LocaleKey.trackStepsBurnCaloriesMeasureDistance:
      "Track Steps, Burn Calories, Measure Distance",
  LocaleKey.caloriesCounter: "Calories Counter",
  LocaleKey.trackYourIntakeMonitorCaloriesStayBalanced:
      "Track Your Intake: Monitor Calories, Stay Balanced",
  LocaleKey.startWorkout: "Start Workout",
  LocaleKey.getPremiumToday: "Get Premium Today",
  LocaleKey.generalSettings: "General Settings",
  LocaleKey.goPremium: "Go PREMIUM",
  LocaleKey.unlockAllFeatures: "Unlock all features",
  LocaleKey.language: "Language",
  LocaleKey.privacyPolicy: "Privacy Policy",
  LocaleKey.checkForUpdate: "Check for update",
  LocaleKey.support: "Support",
  LocaleKey.rateUs: "Rate Us",
  LocaleKey.shareApp: "Share App",
  LocaleKey.contactUs: "Contact Us",
  LocaleKey.whatIncluded: "What's Included?",
  LocaleKey.yearly: "Yearly",
  LocaleKey.monthly: "Monthly",
  LocaleKey.weekly: "Weekly",
  LocaleKey.removeAds: "Remove Ads",
  LocaleKey.useAppSmoothly: "Use App Smoothly",
  LocaleKey.getPremiumNow: "Get Premium Now >",
  LocaleKey.restorePurchase: "Restore Purchase",
  LocaleKey.byPlacingOrder: "By placing this order, you agree to the ",
  LocaleKey.termsOfService: "Terms of Service ",
  LocaleKey.and: "and ",
  LocaleKey.subPrivacyPolicy: "Privacy Policy. ",
  LocaleKey.subsDescription:
      "Without commitment, you can cancel whenever you want. if you don't cancel the subscription 24 hour before the end of the current period, you will be automatically changed through your play store account.\nEven if you don't subscribe you can still use all the free feature.",
  LocaleKey.weValueYourFeedback: "We value your feedback!",
  LocaleKey.sorryForTheInconvenience: "Sorry for the inconvenience.",
  LocaleKey.pleaseShareYourThoughtsToHelpUsImprove:
      "Please share your thoughts to help us improve.",
  LocaleKey.whatAPity: "What a pity!",
  LocaleKey.pleaseLetUsKnowIfYouHaveAnyFeedbackOrSuggestions:
      "Please let us know if you have any feedback or suggestions.",
  LocaleKey.thankYouForYourSupport: "Thank you for your support!",
  LocaleKey.weWillContinueToWorkHardForBetterUserExperience:
      "We will continue to work hard for a better user experience!",
  LocaleKey.thanksMillion: "Thanks a million!",
  LocaleKey.yourSatisfactionMakesAllOfOurEffortWorthwhile:
      "Your satisfaction makes all of our effort worthwhile!",
  LocaleKey.settings: "Settings",
  LocaleKey.stepGoal: "Step goal",
  LocaleKey.save: "Save",
  LocaleKey.cancel: "Cancel",
  LocaleKey.startYourWorkout: "Start Your Workout",
  LocaleKey.history: "History",
  LocaleKey.duration: "Duration",
  LocaleKey.resume: "Resume",
  LocaleKey.pause: "Pause",
  LocaleKey.finish: "Finish",
  LocaleKey.doYouWannaFinishAndSave: "Do you wanna finish and save?",
  LocaleKey.share: "Share",
  LocaleKey.day: "Day",
  LocaleKey.week: "Week",
  LocaleKey.month: "Month",
  LocaleKey.year: "Year",
  LocaleKey.totalDetails: "Total Details",
  LocaleKey.avgPerDayDetails: "Ave. per day Details",
  LocaleKey.step: "Step",
  LocaleKey.distance: "Distance",
  LocaleKey.burned: "Burned",
  LocaleKey.ok: "OK",
  LocaleKey.bodyMassIndex: "Body Mass Index (BMI)",
  LocaleKey.improveYourHealth: "Improve your health",
  LocaleKey.youHealthy: "You're healthy",
  LocaleKey.loseYourWeight: "Lose your weight",
  LocaleKey.youAtRisk: "You're at risk",
  LocaleKey.youAtSeriousRisk: "You're at serious risk",
  LocaleKey.focusOnNutrientRichFoods:
      "Focus on nutrient-rich foods for healthy weight gain. Consult with a dietitian for personalized guidance",
  LocaleKey.maintainHealth:
      "Maintain balanced habits with nutritious eating, exercise, and stress management for overall well-being.",
  LocaleKey.prioritizeWeightLoss:
      "Prioritize weight loss through healthy eating and regular exercise. Seek professional guidance for sustainable changes.",
  LocaleKey.reduceHealthRisks:
      "Reduce health risks by focusing on balanced diet, exercise, and medical support for weight management.",
  LocaleKey.addressSevereHealth:
      "Address severe health risks through comprehensive lifestyle changes and medical intervention as needed.",
  LocaleKey.urgentSeekMedicalHealth:
      "Urgently seek medical attention and support to manage weight and improve overall health.",
  LocaleKey.height: "Height",
  LocaleKey.weight: "Weight",
  LocaleKey.healthTip: "Health Tip",
  LocaleKey.bodyZone: "Body Zone",
  LocaleKey.stepCounterGPSTracking: "Step Counter - GPS Tracking",
  LocaleKey.newDayFreshStart: "New day, fresh start",
  LocaleKey.loadingAd: "Loading Ad!\nPlease wait...",
  LocaleKey.tieYourShoesItTimeToStepIntoAction:
      "Tie your shoes, it's time to step into action!",
  LocaleKey
          .toEnsureStepCounterGPSTrackingFunctionsWellWeNeedYourPermissionToAccessActivityRecognition:
      "To ensure Step Counter - GPS Tracking functions well, we need your permission to access activity recognition",
  LocaleKey.getStarted: "Get Started",
  LocaleKey.setupComplete: "Setup Complete",
  LocaleKey.yourAppIsNowSetUp: "Your app is now set up.",
  LocaleKey.done: "Done",
  LocaleKey.turnOnNotification: "Turn on notification",
  LocaleKey.toReceiveStatusUpdatesWeNeedYourPermissionToShowYouNotification:
      "To receive status updates, we need your permission to show you notification",
  LocaleKey.notNow: "Not Now",
  LocaleKey.turnOn: "Turn On",
  LocaleKey.enableLocation: "Enable Location",
  LocaleKey.activityRecognition: "Activity Recognition",
  LocaleKey.startTrackingYourSteps: "Start tracking your steps",
  LocaleKey
          .toStartYourStepTrackingJourneyAndUnlockTheFullPotentialOfStepCounterGPSTracking:
      "to start your step tracking journey and unlock the full potential of Step Counter - GPS Tracking. Even if your app is in background or foreground",
  LocaleKey.search: "Search",
  LocaleKey.addTodayMeal: "Add Today's meal",
  LocaleKey.trackDailyCaloriesBySelectingMeals:
      "Track daily calories by selecting meals.",
  LocaleKey.warning: "Warning",
  LocaleKey.areYouSureToDeleteThisItem: "Are you sure to delete this item?",
  LocaleKey.delete: "Delete",
  LocaleKey.approx: "Approx",
  LocaleKey.kCalPerServing: "kCal. per serving",
  LocaleKey.countCalories: "Count Calories",
  LocaleKey.detail: "Detail",
  LocaleKey.addInTodayMeal: "Add in Today's Meal",
  LocaleKey.carbs: "Carbs",
  LocaleKey.carbohydrates: "Carbohydrates",
  LocaleKey.fat: "Fat",
  LocaleKey.protein: "Protein",
  LocaleKey.fiber: "Fiber",
  LocaleKey.netCarbs: "Net Carbs",
  LocaleKey.sodium: "Sodium",
  LocaleKey.potassium: "Potassium",
  LocaleKey.cholesterol: "Cholesterol",
  LocaleKey.calories: "Calories",
  LocaleKey.g: "g",
  LocaleKey.mg: "mg",
  LocaleKey.addedToYourTodayMeal: "added to your today meal",
  LocaleKey.addedIn: "added in",
  LocaleKey.successfullyRemoved: "Successfully removed",
  LocaleKey.pleaseSelectTheImage: "Please select the image",
  LocaleKey.pleaseFillTheFoodNameField: "Please fill the food name field",
  LocaleKey.pleaseFillTheCalories: "Please fill the calories",
  LocaleKey.total: "Total",
  LocaleKey.burnNow: "Burn Now",
  LocaleKey.nutritionInfoPerServing: "Nutrition info per serving",
  LocaleKey.createYourFoodItem: "Create your food item",
  LocaleKey.foodDetails: "Food Details",
  LocaleKey.foodName: "Food Name",
  LocaleKey.servingSizeInfo: "Serving Size Info",
  LocaleKey.theNutritionValuesShouldBeApplyOnPerServing:
      "The Nutrition values should be apply on per serving",
  LocaleKey.amountToEat: "Amount to eat",
  LocaleKey.createYourOwnFood: "Create your own food",
  LocaleKey.gallery: "Gallery",
  LocaleKey.camera: "Camera",
  LocaleKey.selectGender: "Select Gender",
  LocaleKey.caloriesStrideLengthCalculationNeedsIt:
      "Calories & stride length calculation needs it...",
  LocaleKey.male: "Male",
  LocaleKey.female: "Female",
  LocaleKey.pleaseSelectTheGender: "Please select the gender",
  LocaleKey.pleaseFillRealData: "Note: Please fill a real data",
  LocaleKey.whatYourAge: "What's your age?",
  LocaleKey.ageInYears: "Age in years",
  LocaleKey.years: "Years",
  LocaleKey.back: "Back",
  LocaleKey.next: "Next",
  LocaleKey.plzSelectYourAge: "Please select your age",
  LocaleKey.howTallAreYou: "How tall are you?",
  LocaleKey.heightInCms: "Height in centimeter(s)",
  LocaleKey.heightInFts: "Height in feet(s)",
  LocaleKey.plzSelectHeight: "Please select your height",
  LocaleKey.cm: "Cm",
  LocaleKey.ft: "Ft",
  LocaleKey.yourCurrentWeight: "Your current weight?",
  LocaleKey.weightInKgs: "weight in kilogram(s)",
  LocaleKey.weightInPounds: "weight in pound(s)",
  LocaleKey.kg: 'Kg',
  LocaleKey.lb: 'Lb',
  LocaleKey.plzSelectWeight: "Please select your weight",
  LocaleKey.locationPermissionDenied: "Location permission is denied",
  LocaleKey.noHistoryExists: "No History Exists",
  LocaleKey.targetDistance: "Target Distance",
  LocaleKey.targetStepsAchievement: "Targeted steps Achievement",
  LocaleKey.yourAreDoingWellTowardsYourGoal:
      "You are doing very well towards your goal",
  LocaleKey.noDataFound: "Oops! No Data Found",
  LocaleKey.contnue: "Continue",
  LocaleKey.subscribedSuccessfully: "Subscribed Successfully",
  LocaleKey.thereAreNoUpgradesAtThisTime: "There are no upgrades at this time",
  LocaleKey.pending: "Pending",
  LocaleKey.noPackageFound: "No Package Found. Try Again Later!",
  LocaleKey.checkYourInternetConnection: "Check your internet connection",
  LocaleKey.noInternet: "No Internet",
  LocaleKey.checkUpdateDesc:
      "Would you like to check the update is available on play store?",
  LocaleKey.check: "Check",
  LocaleKey.stepIntoWellness: "Step into wellness",
  LocaleKey.trackStepsBurnCaloriesLiveHealthier:
      "Track steps, burn calories, live healthier!",
  LocaleKey.exit: "Exit",
  LocaleKey.refresh: "Refresh",
  LocaleKey.billedEvery: "Billed Every",
  LocaleKey.targetCaloriesToBurn: "Target Calories",
  LocaleKey.hurrahYouHitTheTargetCaloriesBurn:
      "Hurrah! 🎊🎉 You've Hit Your Calorie Burn Goal!",
  LocaleKey.routeSaved: "Route Saved",
  LocaleKey.saveYourRoute: "Save Your Route",
  LocaleKey.routeName: "Route Name",
  LocaleKey.saveRoutes: "Save Routes",
  LocaleKey.unknown: "Unknown",
  LocaleKey.route: "Route",
};
