import 'locale_keys.dart';

const Map<String, dynamic> spanishLocalization = {
  LocaleKey.stepCounter: "Contador de Pasos",
  LocaleKey.today: "Hoy",
  LocaleKey.home: "Inicio",
  LocaleKey.activities: "Actividades",
  LocaleKey.goal: "Meta",
  LocaleKey.steps: "pasos",
  LocaleKey.kCal: "kCal",
  LocaleKey.km: "Km",
  LocaleKey.min: "min",
  LocaleKey.setDailyGoal: "¡Establece una meta diaria!",
  LocaleKey.ourInspiredToBetterThemselves:
      "Nuestro 91% inspirado para mejorar.",
  LocaleKey.setNow: "Establecer Ahora",
  LocaleKey.healthTracker: "Seguimiento de Salud",
  LocaleKey.trendsInsights: "Tendencias e Ideas",
  LocaleKey.navigateYourPath: "Navega Tu Camino",
  LocaleKey.weightBMI: "Peso y IMC",
  LocaleKey.cultivateWellnessTrackWeightMeasureHealth:
      "Cultiva el Bienestar: Sigue el Peso, Mide la Salud",
  LocaleKey.gpsTracking: "Rastreo GPS",
  LocaleKey.trackStepsBurnCaloriesMeasureDistance:
      "Rastrea Pasos, Quema Calorías, Mide Distancia",
  LocaleKey.caloriesCounter: "Contador de Calorías",
  LocaleKey.trackYourIntakeMonitorCaloriesStayBalanced:
      "Rastrea tu Consumo: Monitorea Calorías, Mantente Equilibrado",
  LocaleKey.startWorkout: "Comenzar Entrenamiento",
  LocaleKey.getPremiumToday: "Obtén Premium Hoy",
  LocaleKey.generalSettings: "Configuración General",
  LocaleKey.goPremium: "Obtener PREMIUM",
  LocaleKey.unlockAllFeatures: "Desbloquear todas las características",
  LocaleKey.language: "Idioma",
  LocaleKey.privacyPolicy: "Política de Privacidad",
  LocaleKey.checkForUpdate: "Buscar actualización",
  LocaleKey.support: "Soporte",
  LocaleKey.rateUs: "Califícanos",
  LocaleKey.shareApp: "Compartir Aplicación",
  LocaleKey.contactUs: "Contáctanos",
  LocaleKey.whatIncluded: "¿Qué incluye?",
  LocaleKey.yearly: "Anual",
  LocaleKey.monthly: "Mensual",
  LocaleKey.weekly: "Semanal",
  LocaleKey.removeAds: "Eliminar Anuncios",
  LocaleKey.useAppSmoothly: "Usar la Aplicación sin Problemas",
  LocaleKey.getPremiumNow: "¡Obtén Premium Ahora >",
  LocaleKey.restorePurchase: "Restaurar Compra",
  LocaleKey.byPlacingOrder: "Al realizar este pedido, aceptas los ",
  LocaleKey.termsOfService: "Términos de Servicio ",
  LocaleKey.and: "y ",
  LocaleKey.subPrivacyPolicy: "Política de Privacidad. ",
  LocaleKey.subsDescription:
      "Sin compromiso, puedes cancelar cuando quieras. Si no cancelas la suscripción 24 horas antes del final del período actual, se te cobrará automáticamente a través de tu cuenta de Play Store.\nIncluso si no te suscribes, aún puedes usar todas las funciones gratuitas.",
  LocaleKey.weValueYourFeedback: "¡Valoramos tus comentarios!",
  LocaleKey.sorryForTheInconvenience: "Disculpa las molestias.",
  LocaleKey.pleaseShareYourThoughtsToHelpUsImprove:
      "Por favor, comparte tus pensamientos para ayudarnos a mejorar.",
  LocaleKey.whatAPity: "¡Qué lástima!",
  LocaleKey.pleaseLetUsKnowIfYouHaveAnyFeedbackOrSuggestions:
      "Por favor, háznos saber si tienes algún comentario o sugerencia.",
  LocaleKey.thankYouForYourSupport: "¡Gracias por tu apoyo!",
  LocaleKey.weWillContinueToWorkHardForBetterUserExperience:
      "¡Continuaremos trabajando duro para una mejor experiencia de usuario!",
  LocaleKey.thanksMillion: "¡Mil gracias!",
  LocaleKey.yourSatisfactionMakesAllOfOurEffortWorthwhile:
      "¡Tu satisfacción hace que todo nuestro esfuerzo valga la pena!",
  LocaleKey.settings: "Configuración",
  LocaleKey.stepGoal: "Meta de pasos",
  LocaleKey.save: "Guardar",
  LocaleKey.cancel: "Cancelar",
  LocaleKey.startYourWorkout: "Comenzar tu entrenamiento",
  LocaleKey.history: "Historial",
  LocaleKey.duration: "Duración",
  LocaleKey.resume: "Reanudar",
  LocaleKey.pause: "Pausa",
  LocaleKey.finish: "Finalizar",
  LocaleKey.doYouWannaFinishAndSave: "¿Quieres finalizar y guardar?",
  LocaleKey.share: "Compartir",
  LocaleKey.day: "Día",
  LocaleKey.week: "Semana",
  LocaleKey.month: "Mes",
  LocaleKey.year: "Año",
  LocaleKey.totalDetails: "Detalles totales",
  LocaleKey.avgPerDayDetails: "Prom. por día Detalles",
  LocaleKey.step: "Paso",
  LocaleKey.distance: "Distancia",
  LocaleKey.burned: "Quemado",
  LocaleKey.ok: "OK",
  LocaleKey.bodyMassIndex: "Índice de Masa Corporal (IMC)",
  LocaleKey.improveYourHealth: "Mejora tu salud",
  LocaleKey.youHealthy: "Estás sano",
  LocaleKey.loseYourWeight: "Pierde peso",
  LocaleKey.youAtRisk: "Estás en riesgo",
  LocaleKey.youAtSeriousRisk: "Estás en riesgo grave",
  LocaleKey.focusOnNutrientRichFoods:
      "Enfócate en alimentos ricos en nutrientes para ganar peso de manera saludable. Consulta con un dietista para obtener orientación personalizada.",
  LocaleKey.maintainHealth:
      "Mantén hábitos equilibrados con una alimentación nutritiva, ejercicio y manejo del estrés para el bienestar general.",
  LocaleKey.prioritizeWeightLoss:
      "Prioriza la pérdida de peso mediante una alimentación saludable y ejercicio regular. Busca orientación profesional para cambios sostenibles.",
  LocaleKey.reduceHealthRisks:
      "Reduce los riesgos para la salud enfocándote en una dieta equilibrada, ejercicio y apoyo médico para el control del peso.",
  LocaleKey.addressSevereHealth:
      "Aborda los riesgos graves para la salud mediante cambios de estilo de vida integrales e intervención médica según sea necesario.",
  LocaleKey.urgentSeekMedicalHealth:
      "Busca atención médica de manera urgente y apoyo para controlar el peso y mejorar la salud en general.",
  LocaleKey.height: "Altura",
  LocaleKey.weight: "Peso",
  LocaleKey.healthTip: "Consejo de Salud",
  LocaleKey.bodyZone: "Zona del Cuerpo",
  LocaleKey.stepCounterGPSTracking: "Contador de Pasos - Seguimiento GPS",
  LocaleKey.newDayFreshStart: "Nuevo día, nuevo comienzo",
  LocaleKey.loadingAd: "Cargando Anuncio!\nPor favor, espere...",
  LocaleKey.tieYourShoesItTimeToStepIntoAction:
      "¡Ata tus zapatos, es hora de actuar!",
  LocaleKey
          .toEnsureStepCounterGPSTrackingFunctionsWellWeNeedYourPermissionToAccessActivityRecognition:
      "Para garantizar que el Contador de Pasos - Seguimiento GPS funcione correctamente, necesitamos tu permiso para acceder al reconocimiento de actividad",
  LocaleKey.getStarted: "Empezar",
  LocaleKey.setupComplete: "Configuración Completa",
  LocaleKey.yourAppIsNowSetUp: "Tu aplicación está ahora configurada.",
  LocaleKey.done: "Listo",
  LocaleKey.turnOnNotification: "Activar Notificaciones",
  LocaleKey.toReceiveStatusUpdatesWeNeedYourPermissionToShowYouNotification:
      "Para recibir actualizaciones de estado, necesitamos tu permiso para mostrarte notificaciones",
  LocaleKey.notNow: "Ahora no",
  LocaleKey.turnOn: "Activar",
  LocaleKey.enableLocation: "Activar Ubicación",
  LocaleKey.activityRecognition: "Reconocimiento de Actividad",
  LocaleKey.startTrackingYourSteps: "Comenzar a rastrear tus pasos",
  LocaleKey
          .toStartYourStepTrackingJourneyAndUnlockTheFullPotentialOfStepCounterGPSTracking:
      "para comenzar tu viaje de seguimiento de pasos y desbloquear todo el potencial del Contador de Pasos - Seguimiento GPS. Incluso si tu aplicación está en segundo plano o en primer plano",
  LocaleKey.search: "Buscar",
  LocaleKey.addTodayMeal: "Agregar comida de hoy",
  LocaleKey.trackDailyCaloriesBySelectingMeals:
      "Rastrea las calorías diarias seleccionando comidas.",
  LocaleKey.warning: "Advertencia",
  LocaleKey.areYouSureToDeleteThisItem:
      "¿Estás seguro de eliminar este elemento?",
  LocaleKey.delete: "Eliminar",
  LocaleKey.approx: "Aprox",
  LocaleKey.kCalPerServing: "kCal. por porción",
  LocaleKey.countCalories: "Contar Calorías",
  LocaleKey.detail: "Detalle",
  LocaleKey.addInTodayMeal: "Agregar en la comida de hoy",
  LocaleKey.carbs: "Carbohidratos",
  LocaleKey.carbohydrates: "Carbohidratos",
  LocaleKey.fat: "Grasa",
  LocaleKey.protein: "Proteína",
  LocaleKey.fiber: "Fibra",
  LocaleKey.netCarbs: "Carbohidratos Netos",
  LocaleKey.sodium: "Sodio",
  LocaleKey.potassium: "Potasio",
  LocaleKey.cholesterol: "Colesterol",
  LocaleKey.calories: "Calorías",
  LocaleKey.g: "g",
  LocaleKey.mg: "mg",
  LocaleKey.addedToYourTodayMeal: "agregado a tu comida de hoy",
  LocaleKey.addedIn: "agregado en",
  LocaleKey.successfullyRemoved: "Eliminado con éxito",
  LocaleKey.pleaseSelectTheImage: "Por favor selecciona la imagen",
  LocaleKey.pleaseFillTheFoodNameField:
      "Por favor rellena el campo de nombre del alimento",
  LocaleKey.pleaseFillTheCalories: "Por favor rellena las calorías",
  LocaleKey.total: "Total",
  LocaleKey.burnNow: "Quemar Ahora",
  LocaleKey.nutritionInfoPerServing: "Información nutricional por porción",
  LocaleKey.createYourFoodItem: "Crea tu comida",
  LocaleKey.foodDetails: "Detalles del alimento",
  LocaleKey.foodName: "Nombre del alimento",
  LocaleKey.servingSizeInfo: "Información del tamaño de la porción",
  LocaleKey.theNutritionValuesShouldBeApplyOnPerServing:
      "Los valores nutricionales deben aplicarse por porción",
  LocaleKey.amountToEat: "Cantidad para comer",
  LocaleKey.createYourOwnFood: "Crea tu propio alimento",
  LocaleKey.gallery: "Galería",
  LocaleKey.camera: "Cámara",
  LocaleKey.selectGender: "Seleccionar género",
  LocaleKey.caloriesStrideLengthCalculationNeedsIt:
      "¡Los cálculos de calorías y longitud de zancada lo necesitan!",
  LocaleKey.male: "Masculino",
  LocaleKey.female: "Femenino",
  LocaleKey.pleaseSelectTheGender: "Por favor seleccione el género",
  LocaleKey.pleaseFillRealData: "Nota: Por favor, introduzca datos reales",
  LocaleKey.whatYourAge: "¿Cuál es tu edad?",
  LocaleKey.ageInYears: "Edad en años",
  LocaleKey.years: "Años",
  LocaleKey.back: "Atrás",
  LocaleKey.next: "Siguiente",
  LocaleKey.plzSelectYourAge: "Por favor, seleccione su edad",
  LocaleKey.howTallAreYou: "¿Cuánto mides?",
  LocaleKey.heightInCms: "Altura en centímetros",
  LocaleKey.heightInFts: "Altura en pies",
  LocaleKey.plzSelectHeight: "Por favor, seleccione su altura",
  LocaleKey.cm: "cm",
  LocaleKey.ft: "pies",
  LocaleKey.yourCurrentWeight: "¿Cuál es tu peso actual?",
  LocaleKey.weightInKgs: "Peso en kilogramos",
  LocaleKey.weightInPounds: "Peso en libras",
  LocaleKey.kg: "kg",
  LocaleKey.lb: "lb",
  LocaleKey.plzSelectWeight: "Por favor, seleccione su peso",
  LocaleKey.locationPermissionDenied: "Se ha denegado el permiso de ubicación",
  LocaleKey.noHistoryExists: "No existe historial",
  LocaleKey.targetDistance: "Distancia objetivo",
  LocaleKey.targetStepsAchievement: "Logro de pasos objetivo",
  LocaleKey.yourAreDoingWellTowardsYourGoal:
      "Estás avanzando bien hacia tu objetivo",
  LocaleKey.noDataFound: "¡Ups! No se Encontraron Datos.",
  LocaleKey.contnue: "Continuar",
  LocaleKey.subscribedSuccessfully: "Suscripción realizada con éxito",
  LocaleKey.thereAreNoUpgradesAtThisTime:
      "No hay actualizaciones en este momento",
  LocaleKey.pending: "Pendiente",
  LocaleKey.noPackageFound:
      "Paquete no encontrado. ¡Inténtalo de nuevo más tarde!",
  LocaleKey.checkYourInternetConnection: "Verifique su conexión a internet.",
  LocaleKey.noInternet: "Sin Internet",
  LocaleKey.checkUpdateDesc:
      "¿Quieres verificar si hay actualizaciones disponibles en la Play Store?",
  LocaleKey.check: "Comprobar",
  LocaleKey.stepIntoWellness: "Da un paso hacia el bienestar",
  LocaleKey.trackStepsBurnCaloriesLiveHealthier:
      "Rastrea pasos, quema calorías, ¡vive más saludable!",
  LocaleKey.exit: "Salir",
  LocaleKey.refresh: "Actualizar",
  LocaleKey.billedEvery: "Facturado Cada",
  LocaleKey.targetCaloriesToBurn: "Calorías Objetivo a Quemar",
  LocaleKey.hurrahYouHitTheTargetCaloriesBurn:
      "¡Hurra! 🎊🎉 ¡Has alcanzado tu objetivo de quema de calorías!",
  LocaleKey.routeSaved: "Ruta Guardada",
  LocaleKey.saveYourRoute: "Guarda Tu Ruta",
  LocaleKey.routeName: "Nombre de la Ruta",
  LocaleKey.saveRoutes: "Guardar Rutas",
  LocaleKey.unknown: "Desconocido",
  LocaleKey.route: "Ruta",
};
