import 'locale_keys.dart';

const Map<String, dynamic> frenchLocalization = {
  LocaleKey.stepCounter: "Compteur de Pas",
  LocaleKey.today: "Aujourd'hui",
  LocaleKey.home: "Accueil",
  LocaleKey.activities: "Activités",
  LocaleKey.goal: "Objectif",
  LocaleKey.steps: "pas",
  LocaleKey.kCal: "kCal",
  LocaleKey.km: "Km",
  LocaleKey.min: "min",
  LocaleKey.setDailyGoal: "Définir un objectif quotidien !",
  LocaleKey.ourInspiredToBetterThemselves:
      "Nos 91% sont inspirés pour s'améliorer.",
  LocaleKey.setNow: "Définir Maintenant",
  LocaleKey.healthTracker: "Suivi de Santé",
  LocaleKey.trendsInsights: "Tendances et Analyses",
  LocaleKey.navigateYourPath: "Naviguer Votre Chemin",
  LocaleKey.weightBMI: "Poids et IMC",
  LocaleKey.cultivateWellnessTrackWeightMeasureHealth:
      "Cultiver le Bien-être : Suivre le Poids, Mesurer la Santé",
  LocaleKey.gpsTracking: "Suivi GPS",
  LocaleKey.trackStepsBurnCaloriesMeasureDistance:
      "Suivre les Pas, Brûler les Calories, Mesurer la Distance",
  LocaleKey.caloriesCounter: "Compteur de Calories",
  LocaleKey.trackYourIntakeMonitorCaloriesStayBalanced:
      "Suivre votre Apport : Surveiller les Calories, Rester Équilibré",
  LocaleKey.startWorkout: "Commencer l'Entraînement",
  LocaleKey.getPremiumToday: "Obtenez Premium Aujourd'hui",
  LocaleKey.generalSettings: "Paramètres Généraux",
  LocaleKey.goPremium: "Passer à PREMIUM",
  LocaleKey.unlockAllFeatures: "Débloquer toutes les fonctionnalités",
  LocaleKey.language: "Langue",
  LocaleKey.privacyPolicy: "Politique de Confidentialité",
  LocaleKey.checkForUpdate: "Vérifier les mises à jour",
  LocaleKey.support: "Support",
  LocaleKey.rateUs: "Notez-nous",
  LocaleKey.shareApp: "Partager l'Application",
  LocaleKey.contactUs: "Nous Contacter",
  LocaleKey.whatIncluded: "Qu'est-ce qui est inclus ?",
  LocaleKey.yearly: "Annuel",
  LocaleKey.monthly: "Mensuel",
  LocaleKey.weekly: "Hebdomadaire",
  LocaleKey.removeAds: "Supprimer les Publicités",
  LocaleKey.useAppSmoothly: "Utiliser l'Application en Toute Fluidité",
  LocaleKey.getPremiumNow: "Obtenez Premium Maintenant >",
  LocaleKey.restorePurchase: "Restaurer l'Achat",
  LocaleKey.byPlacingOrder: "En passant cette commande, vous acceptez les ",
  LocaleKey.termsOfService: "Conditions d'Utilisation ",
  LocaleKey.and: "et ",
  LocaleKey.subPrivacyPolicy: "Politique de Confidentialité. ",
  LocaleKey.subsDescription:
      "Sans engagement, vous pouvez annuler quand vous le souhaitez. Si vous n'annulez pas l'abonnement 24 heures avant la fin de la période en cours, vous serez automatiquement facturé via votre compte Play Store.\nMême si vous ne vous abonnez pas, vous pouvez toujours utiliser toutes les fonctionnalités gratuites.",
  LocaleKey.weValueYourFeedback: "Nous apprécions vos commentaires !",
  LocaleKey.sorryForTheInconvenience: "Désolé pour le désagrément.",
  LocaleKey.pleaseShareYourThoughtsToHelpUsImprove:
      "Veuillez partager vos pensées pour nous aider à nous améliorer.",
  LocaleKey.whatAPity: "Quel dommage !",
  LocaleKey.pleaseLetUsKnowIfYouHaveAnyFeedbackOrSuggestions:
      "Veuillez nous informer si vous avez des commentaires ou des suggestions.",
  LocaleKey.thankYouForYourSupport: "Merci pour votre soutien !",
  LocaleKey.weWillContinueToWorkHardForBetterUserExperience:
      "Nous continuerons à travailler dur pour une meilleure expérience utilisateur !",
  LocaleKey.thanksMillion: "Merci mille fois !",
  LocaleKey.yourSatisfactionMakesAllOfOurEffortWorthwhile:
      "Votre satisfaction rend tout notre effort précieux !",
  LocaleKey.settings: "Paramètres",
  LocaleKey.stepGoal: "Objectif de pas",
  LocaleKey.save: "Enregistrer",
  LocaleKey.cancel: "Annuler",
  LocaleKey.startYourWorkout: "Commencer votre entraînement",
  LocaleKey.history: "Historique",
  LocaleKey.duration: "Durée",
  LocaleKey.resume: "Reprendre",
  LocaleKey.pause: "Pause",
  LocaleKey.finish: "Terminer",
  LocaleKey.doYouWannaFinishAndSave: "Voulez-vous terminer et enregistrer?",
  LocaleKey.share: "Partager",
  LocaleKey.day: "Jour",
  LocaleKey.week: "Semaine",
  LocaleKey.month: "Mois",
  LocaleKey.year: "An",
  LocaleKey.totalDetails: "Détails totaux",
  LocaleKey.avgPerDayDetails: "Moy. par jour Détails",
  LocaleKey.step: "Pas",
  LocaleKey.distance: "Distance",
  LocaleKey.burned: "Brûlé",
  LocaleKey.ok: "OK",
  LocaleKey.bodyMassIndex: "Indice de Masse Corporelle (IMC)",
  LocaleKey.improveYourHealth: "Améliorez votre santé",
  LocaleKey.youHealthy: "Vous êtes en bonne santé",
  LocaleKey.loseYourWeight: "Perdez du poids",
  LocaleKey.youAtRisk: "Vous êtes à risque",
  LocaleKey.youAtSeriousRisk: "Vous êtes en risque grave",
  LocaleKey.focusOnNutrientRichFoods:
      "Concentrez-vous sur les aliments riches en nutriments pour une prise de poids saine. Consultez un nutritionniste pour des conseils personnalisés.",
  LocaleKey.maintainHealth:
      "Maintenez des habitudes équilibrées avec une alimentation nutritive, de l'exercice et une gestion du stress pour un bien-être général.",
  LocaleKey.prioritizeWeightLoss:
      "Donnez la priorité à la perte de poids grâce à une alimentation saine et à des exercices réguliers. Cherchez un accompagnement professionnel pour des changements durables.",
  LocaleKey.reduceHealthRisks:
      "Réduisez les risques pour la santé en vous concentrant sur une alimentation équilibrée, de l'exercice et un soutien médical pour la gestion du poids.",
  LocaleKey.addressSevereHealth:
      "Adressez-vous aux risques de santé graves grâce à des changements de mode de vie complets et une intervention médicale si nécessaire.",
  LocaleKey.urgentSeekMedicalHealth:
      "Recherchez de toute urgence une attention médicale et un soutien pour gérer le poids et améliorer la santé générale.",
  LocaleKey.height: "Taille",
  LocaleKey.weight: "Poids",
  LocaleKey.healthTip: "Conseil de Santé",
  LocaleKey.bodyZone: "Zone du Corps",
  LocaleKey.stepCounterGPSTracking: "Compteur de Pas - Suivi GPS",
  LocaleKey.newDayFreshStart: "Nouveau jour, nouveau départ",
  LocaleKey.loadingAd: "Chargement de la Publicité!\nVeuillez patienter...",
  LocaleKey.tieYourShoesItTimeToStepIntoAction:
      "Attachez vos chaussures, il est temps d'agir !",
  LocaleKey
          .toEnsureStepCounterGPSTrackingFunctionsWellWeNeedYourPermissionToAccessActivityRecognition:
      "Pour garantir que le Compteur de Pas - Suivi GPS fonctionne correctement, nous avons besoin de votre autorisation pour accéder à la reconnaissance d'activité",
  LocaleKey.getStarted: "Commencer",
  LocaleKey.setupComplete: "Configuration Terminée",
  LocaleKey.yourAppIsNowSetUp: "Votre application est maintenant configurée.",
  LocaleKey.done: "Terminé",
  LocaleKey.turnOnNotification: "Activer les Notifications",
  LocaleKey.toReceiveStatusUpdatesWeNeedYourPermissionToShowYouNotification:
      "Pour recevoir les mises à jour de statut, nous avons besoin de votre permission pour vous montrer des notifications",
  LocaleKey.notNow: "Pas Maintenant",
  LocaleKey.turnOn: "Activer",
  LocaleKey.enableLocation: "Activer la Localisation",
  LocaleKey.activityRecognition: "Reconnaissance d'Activité",
  LocaleKey.startTrackingYourSteps: "Commencer à suivre vos pas",
  LocaleKey
          .toStartYourStepTrackingJourneyAndUnlockTheFullPotentialOfStepCounterGPSTracking:
      "pour commencer votre parcours de suivi des pas et débloquer tout le potentiel du Compteur de Pas - Suivi GPS. Même si votre application est en arrière-plan ou en avant-plan",
  LocaleKey.search: "Rechercher",
  LocaleKey.addTodayMeal: "Ajouter le repas d'aujourd'hui",
  LocaleKey.trackDailyCaloriesBySelectingMeals:
      "Suivez les calories quotidiennes en sélectionnant des repas.",
  LocaleKey.warning: "Attention",
  LocaleKey.areYouSureToDeleteThisItem:
      "Êtes-vous sûr de vouloir supprimer cet élément?",
  LocaleKey.delete: "Supprimer",
  LocaleKey.approx: "Env.",
  LocaleKey.kCalPerServing: "kCal. par portion",
  LocaleKey.countCalories: "Compter les Calories",
  LocaleKey.detail: "Détail",
  LocaleKey.addInTodayMeal: "Ajouter dans le repas d'aujourd'hui",
  LocaleKey.carbs: "Glucides",
  LocaleKey.carbohydrates: "Glucides",
  LocaleKey.fat: "Graisses",
  LocaleKey.protein: "Protéines",
  LocaleKey.fiber: "Fibres",
  LocaleKey.netCarbs: "Glucides nets",
  LocaleKey.sodium: "Sodium",
  LocaleKey.potassium: "Potassium",
  LocaleKey.cholesterol: "Cholestérol",
  LocaleKey.calories: "Calories",
  LocaleKey.g: "g",
  LocaleKey.mg: "mg",
  LocaleKey.addedToYourTodayMeal: "ajouté à votre repas d'aujourd'hui",
  LocaleKey.addedIn: "ajouté dans",
  LocaleKey.successfullyRemoved: "Supprimé avec succès",
  LocaleKey.pleaseSelectTheImage: "Veuillez sélectionner l'image",
  LocaleKey.pleaseFillTheFoodNameField:
      "Veuillez remplir le champ du nom de l'aliment",
  LocaleKey.pleaseFillTheCalories: "Veuillez remplir les calories",
  LocaleKey.total: "Total",
  LocaleKey.burnNow: "Brûler Maintenant",
  LocaleKey.nutritionInfoPerServing: "Informations nutritionnelles par portion",
  LocaleKey.createYourFoodItem: "Créez votre aliment",
  LocaleKey.foodDetails: "Détails de l'aliment",
  LocaleKey.foodName: "Nom de l'aliment",
  LocaleKey.servingSizeInfo: "Informations sur la taille de la portion",
  LocaleKey.theNutritionValuesShouldBeApplyOnPerServing:
      "Les valeurs nutritionnelles doivent être appliquées par portion",
  LocaleKey.amountToEat: "Quantité à manger",
  LocaleKey.createYourOwnFood: "Créez votre propre aliment",
  LocaleKey.gallery: "Galerie",
  LocaleKey.camera: "Appareil photo",
  LocaleKey.selectGender: "Sélectionner le genre",
  LocaleKey.caloriesStrideLengthCalculationNeedsIt:
      "Les calculs de calories et de longueur de foulée en ont besoin...",
  LocaleKey.male: "Homme",
  LocaleKey.female: "Femme",
  LocaleKey.pleaseSelectTheGender: "Veuillez sélectionner le genre",
  LocaleKey.pleaseFillRealData:
      "Remarque : Veuillez remplir des données réelles",
  LocaleKey.whatYourAge: "Quel est votre âge ?",
  LocaleKey.ageInYears: "Âge en années",
  LocaleKey.years: "Ans",
  LocaleKey.back: "Retour",
  LocaleKey.next: "Suivant",
  LocaleKey.plzSelectYourAge: "Veuillez sélectionner votre âge",
  LocaleKey.howTallAreYou: "Quelle est votre taille ?",
  LocaleKey.heightInCms: "Taille en centimètres",
  LocaleKey.heightInFts: "Taille en pieds",
  LocaleKey.plzSelectHeight: "Veuillez sélectionner votre taille",
  LocaleKey.cm: "cm",
  LocaleKey.ft: "pieds",
  LocaleKey.yourCurrentWeight: "Quel est votre poids actuel ?",
  LocaleKey.weightInKgs: "Poids en kilogrammes",
  LocaleKey.weightInPounds: "Poids en livres",
  LocaleKey.kg: "kg",
  LocaleKey.lb: "lb",
  LocaleKey.plzSelectWeight: "Veuillez sélectionner votre poids",
  LocaleKey.locationPermissionDenied:
      "La permission de localisation est refusée",
  LocaleKey.noHistoryExists: "Aucun historique n'existe",
  LocaleKey.targetDistance: "Distance cible",
  LocaleKey.targetStepsAchievement: "Réussite des pas cibles",
  LocaleKey.yourAreDoingWellTowardsYourGoal:
      "Vous progressez bien vers votre objectif",
  LocaleKey.noDataFound: "Oups ! Aucune Donnée Trouvée.",
  LocaleKey.contnue: "Continuer",
  LocaleKey.subscribedSuccessfully: "Abonnement réussi",
  LocaleKey.thereAreNoUpgradesAtThisTime:
      "Il n'y a pas de mises à niveau pour le moment",
  LocaleKey.pending: "En attente",
  LocaleKey.noPackageFound: "Aucun paquet trouvé. Réessayez plus tard !",
  LocaleKey.checkYourInternetConnection: "Vérifiez votre connexion internet.",
  LocaleKey.noInternet: "Pas d'Internet",
  LocaleKey.checkUpdateDesc:
      "Souhaitez-vous vérifier si des mises à jour sont disponibles sur le Play Store?",
  LocaleKey.check: "Vérifier",
  LocaleKey.stepIntoWellness: "Entrez dans le bien-être",
  LocaleKey.trackStepsBurnCaloriesLiveHealthier:
      "Suivez vos pas, brûlez des calories, vivez plus sainement !",
  LocaleKey.exit: "Quitter",
  LocaleKey.refresh: "Rafraîchir",
  LocaleKey.billedEvery: "Facturé Tous les",
  LocaleKey.targetCaloriesToBurn: "Calories Ciblées à Brûler",
  LocaleKey.hurrahYouHitTheTargetCaloriesBurn:
      "Hourra! 🎊🎉 Vous avez atteint votre objectif de brûlage de calories!",
  LocaleKey.routeSaved: "Itinéraire Enregistré",
  LocaleKey.saveYourRoute: "Enregistrez Votre Itinéraire",
  LocaleKey.routeName: "Nom de l'Itinéraire",
  LocaleKey.saveRoutes: "Enregistrer les Itinéraires",
  LocaleKey.unknown: "Inconnu",
  LocaleKey.route: "Itinéraire",
};
