import 'locale_keys.dart';

const Map<String, dynamic> portugueseLocalization = {
  LocaleKey.stepCounter: "Contador de Passos",
  LocaleKey.today: "Hoje",
  LocaleKey.home: "Início",
  LocaleKey.activities: "Atividades",
  LocaleKey.goal: "Meta",
  LocaleKey.steps: "passos",
  LocaleKey.kCal: "kCal",
  LocaleKey.km: "Km",
  LocaleKey.min: "min",
  LocaleKey.setDailyGoal: "Defina uma meta diária!",
  LocaleKey.ourInspiredToBetterThemselves:
      "Nós, 91%, inspirados a melhorar a si mesmos.",
  LocaleKey.setNow: "Definir Agora",
  LocaleKey.healthTracker: "Rastreador de Saúde",
  LocaleKey.trendsInsights: "Tendências e Insights",
  LocaleKey.navigateYourPath: "Navegue Seu Caminho",
  LocaleKey.weightBMI: "Peso e IMC",
  LocaleKey.cultivateWellnessTrackWeightMeasureHealth:
      "Cultive o Bem-Estar: Acompanhe o Peso, Meça a Saúde",
  LocaleKey.gpsTracking: "Rastreamento GPS",
  LocaleKey.trackStepsBurnCaloriesMeasureDistance:
      "Acompanhe os Passos, Queime Calorias, Meça a Distância",
  LocaleKey.caloriesCounter: "Contador de Calorias",
  LocaleKey.trackYourIntakeMonitorCaloriesStayBalanced:
      "Acompanhe sua Ingestão: Monitore Calorias, Mantenha o Equilíbrio",
  LocaleKey.startWorkout: "Iniciar Treino",
  LocaleKey.getPremiumToday: "Obtenha Premium Hoje",
  LocaleKey.generalSettings: "Configurações Gerais",
  LocaleKey.goPremium: "Ir PREMIUM",
  LocaleKey.unlockAllFeatures: "Desbloquear todas as funcionalidades",
  LocaleKey.language: "Idioma",
  LocaleKey.privacyPolicy: "Política de Privacidade",
  LocaleKey.checkForUpdate: "Verificar atualização",
  LocaleKey.support: "Suporte",
  LocaleKey.rateUs: "Avalie-nos",
  LocaleKey.shareApp: "Compartilhar Aplicativo",
  LocaleKey.contactUs: "Contate-nos",
  LocaleKey.whatIncluded: "O que está incluído?",
  LocaleKey.yearly: "Anual",
  LocaleKey.monthly: "Mensal",
  LocaleKey.weekly: "Semanal",
  LocaleKey.removeAds: "Remover Anúncios",
  LocaleKey.useAppSmoothly: "Usar o aplicativo sem problemas",
  LocaleKey.getPremiumNow: "Obter Premium Agora >",
  LocaleKey.restorePurchase: "Restaurar Compra",
  LocaleKey.byPlacingOrder: "Ao fazer este pedido, você concorda com os ",
  LocaleKey.termsOfService: "Termos de Serviço ",
  LocaleKey.and: "e ",
  LocaleKey.subPrivacyPolicy: "Política de Privacidade. ",
  LocaleKey.subsDescription:
      "Sem compromisso, você pode cancelar quando quiser. Se não cancelar a assinatura 24 horas antes do final do período atual, você será automaticamente cobrado através da sua conta na Play Store.\nMesmo que não assine, você ainda pode usar todos os recursos gratuitos.",
  LocaleKey.weValueYourFeedback: "Valorizamos seu feedback!",
  LocaleKey.sorryForTheInconvenience: "Desculpe pelo inconveniente.",
  LocaleKey.pleaseShareYourThoughtsToHelpUsImprove:
      "Por favor, compartilhe seus pensamentos para nos ajudar a melhorar.",
  LocaleKey.whatAPity: "Que pena!",
  LocaleKey.pleaseLetUsKnowIfYouHaveAnyFeedbackOrSuggestions:
      "Por favor, nos avise se você tiver algum feedback ou sugestão.",
  LocaleKey.thankYouForYourSupport: "Obrigado pelo seu apoio!",
  LocaleKey.weWillContinueToWorkHardForBetterUserExperience:
      "Continuaremos trabalhando duro para uma melhor experiência do usuário!",
  LocaleKey.thanksMillion: "Muito obrigado!",
  LocaleKey.yourSatisfactionMakesAllOfOurEffortWorthwhile:
      "Sua satisfação torna todo o nosso esforço valioso!",
  LocaleKey.settings: "Configurações",
  LocaleKey.stepGoal: "Meta de passos",
  LocaleKey.save: "Salvar",
  LocaleKey.cancel: "Cancelar",
  LocaleKey.startYourWorkout: "Iniciar seu treino",
  LocaleKey.history: "Histórico",
  LocaleKey.duration: "Duração",
  LocaleKey.resume: "Continuar",
  LocaleKey.pause: "Pausar",
  LocaleKey.finish: "Finalizar",
  LocaleKey.doYouWannaFinishAndSave: "Você quer finalizar e salvar?",
  LocaleKey.share: "Compartilhar",
  LocaleKey.day: "Dia",
  LocaleKey.week: "Semana",
  LocaleKey.month: "Mês",
  LocaleKey.year: "Ano",
  LocaleKey.totalDetails: "Detalhes Totais",
  LocaleKey.avgPerDayDetails: "Média por dia de Detalhes",
  LocaleKey.step: "Passo",
  LocaleKey.distance: "Distância",
  LocaleKey.burned: "Queimado",
  LocaleKey.ok: "OK",
  LocaleKey.bodyMassIndex: "Índice de Massa Corporal (IMC)",
  LocaleKey.improveYourHealth: "Melhore sua saúde",
  LocaleKey.youHealthy: "Você está saudável",
  LocaleKey.loseYourWeight: "Perca seu peso",
  LocaleKey.youAtRisk: "Você está em risco",
  LocaleKey.youAtSeriousRisk: "Você está em risco grave",
  LocaleKey.focusOnNutrientRichFoods:
      "Concentre-se em alimentos ricos em nutrientes para ganho de peso saudável. Consulte um nutricionista para orientação personalizada.",
  LocaleKey.maintainHealth:
      "Mantenha hábitos equilibrados com alimentação nutritiva, exercícios e manejo do estresse para o bem-estar geral.",
  LocaleKey.prioritizeWeightLoss:
      "Priorize a perda de peso através de uma alimentação saudável e exercícios regulares. Busque orientação profissional para mudanças sustentáveis.",
  LocaleKey.reduceHealthRisks:
      "Reduza os riscos à saúde focando em uma dieta equilibrada, exercícios e suporte médico para o controle do peso.",
  LocaleKey.addressSevereHealth:
      "Aborde riscos à saúde graves através de mudanças de estilo de vida abrangentes e intervenção médica conforme necessário.",
  LocaleKey.urgentSeekMedicalHealth:
      "Procure atendimento médico e suporte urgentemente para gerenciar o peso e melhorar a saúde geral.",
  LocaleKey.height: "Altura",
  LocaleKey.weight: "Peso",
  LocaleKey.healthTip: "Dica de Saúde",
  LocaleKey.bodyZone: "Zona do Corpo",
  LocaleKey.stepCounterGPSTracking: "Contador de Passos - Rastreamento GPS",
  LocaleKey.newDayFreshStart: "Novo dia, novo começo",
  LocaleKey.loadingAd: "Carregando Anúncio!\nPor favor, aguarde...",
  LocaleKey.tieYourShoesItTimeToStepIntoAction:
      "Amarre seus sapatos, é hora de agir!",
  LocaleKey
          .toEnsureStepCounterGPSTrackingFunctionsWellWeNeedYourPermissionToAccessActivityRecognition:
      "Para garantir que o Contador de Passos - Rastreamento GPS funcione bem, precisamos da sua permissão para acessar o reconhecimento de atividade",
  LocaleKey.getStarted: "Começar",
  LocaleKey.setupComplete: "Configuração Completa",
  LocaleKey.yourAppIsNowSetUp: "Seu aplicativo está agora configurado.",
  LocaleKey.done: "Feito",
  LocaleKey.turnOnNotification: "Ativar Notificação",
  LocaleKey.toReceiveStatusUpdatesWeNeedYourPermissionToShowYouNotification:
      "Para receber atualizações de status, precisamos da sua permissão para mostrar notificações",
  LocaleKey.notNow: "Agora não",
  LocaleKey.turnOn: "Ativar",
  LocaleKey.enableLocation: "Ativar Localização",
  LocaleKey.activityRecognition: "Reconhecimento de Atividade",
  LocaleKey.startTrackingYourSteps: "Começar a rastrear seus passos",
  LocaleKey
          .toStartYourStepTrackingJourneyAndUnlockTheFullPotentialOfStepCounterGPSTracking:
      "para começar sua jornada de rastreamento de passos e desbloquear todo o potencial do Contador de Passos - Rastreamento GPS. Mesmo se o seu aplicativo estiver em segundo plano ou em primeiro planoi8",
  LocaleKey.search: "Pesquisar",
  LocaleKey.addTodayMeal: "Adicionar a refeição de hoje",
  LocaleKey.trackDailyCaloriesBySelectingMeals:
      "Acompanhe as calorias diárias selecionando refeições.",
  LocaleKey.warning: "Aviso",
  LocaleKey.areYouSureToDeleteThisItem:
      "Tem certeza de que deseja excluir este item?",
  LocaleKey.delete: "Excluir",
  LocaleKey.approx: "Aprox.",
  LocaleKey.kCalPerServing: "kCal. por porção",
  LocaleKey.countCalories: "Contar Calorias",
  LocaleKey.detail: "Detalhe",
  LocaleKey.addInTodayMeal: "Adicionar na refeição de hoje",
  LocaleKey.carbs: "Carboidratos",
  LocaleKey.carbohydrates: "Carboidratos",
  LocaleKey.fat: "Gordura",
  LocaleKey.protein: "Proteína",
  LocaleKey.fiber: "Fibra",
  LocaleKey.netCarbs: "Carboidratos líquidos",
  LocaleKey.sodium: "Sódio",
  LocaleKey.potassium: "Potássio",
  LocaleKey.cholesterol: "Colesterol",
  LocaleKey.calories: "Calorias",
  LocaleKey.g: "g",
  LocaleKey.mg: "mg",
  LocaleKey.addedToYourTodayMeal: "adicionado à sua refeição de hoje",
  LocaleKey.addedIn: "adicionado em",
  LocaleKey.successfullyRemoved: "Removido com sucesso",
  LocaleKey.pleaseSelectTheImage: "Por favor, selecione a imagem",
  LocaleKey.pleaseFillTheFoodNameField:
      "Por favor, preencha o campo do nome do alimento",
  LocaleKey.pleaseFillTheCalories: "Por favor, preencha as calorias",
  LocaleKey.total: "Total",
  LocaleKey.burnNow: "Queimar Agora",
  LocaleKey.nutritionInfoPerServing: "Informações Nutricionais por Porção",
  LocaleKey.createYourFoodItem: "Crie seu alimento",
  LocaleKey.foodDetails: "Detalhes do Alimento",
  LocaleKey.foodName: "Nome do Alimento",
  LocaleKey.servingSizeInfo: "Informações sobre o Tamanho da Porção",
  LocaleKey.theNutritionValuesShouldBeApplyOnPerServing:
      "Os valores nutricionais devem ser aplicados por porção",
  LocaleKey.amountToEat: "Quantidade para comer",
  LocaleKey.createYourOwnFood: "Crie seu próprio alimento",
  LocaleKey.gallery: "Galeria",
  LocaleKey.camera: "Câmera",
  LocaleKey.selectGender: "Selecione o gênero",
  LocaleKey.caloriesStrideLengthCalculationNeedsIt:
      "Cálculos de calorias e comprimento de passada precisam disso...",
  LocaleKey.male: "Masculino",
  LocaleKey.female: "Feminino",
  LocaleKey.pleaseSelectTheGender: "Por favor, selecione o gênero",
  LocaleKey.pleaseFillRealData: "Nota: Por favor, preencha dados reais",
  LocaleKey.whatYourAge: "Qual é a sua idade?",
  LocaleKey.ageInYears: "Idade em anos",
  LocaleKey.years: "Anos",
  LocaleKey.back: "Voltar",
  LocaleKey.next: "Próximo",
  LocaleKey.plzSelectYourAge: "Por favor, selecione a sua idade",
  LocaleKey.howTallAreYou: "Qual é a sua altura?",
  LocaleKey.heightInCms: "Altura em centímetros",
  LocaleKey.heightInFts: "Altura em pés",
  LocaleKey.plzSelectHeight: "Por favor, selecione a sua altura",
  LocaleKey.cm: "cm",
  LocaleKey.ft: "pés",
  LocaleKey.yourCurrentWeight: "Qual é o seu peso atual?",
  LocaleKey.weightInKgs: "Peso em quilogramas",
  LocaleKey.weightInPounds: "Peso em libras",
  LocaleKey.kg: "kg",
  LocaleKey.lb: "lb",
  LocaleKey.plzSelectWeight: "Por favor, selecione o seu peso",
  LocaleKey.locationPermissionDenied: "Permissão de localização negada",
  LocaleKey.noHistoryExists: "Nenhum histórico disponível",
  LocaleKey.targetDistance: "Distância alvo",
  LocaleKey.targetStepsAchievement: "Alcançamento de passos alvo",
  LocaleKey.yourAreDoingWellTowardsYourGoal:
      "Você está progredindo bem em direção ao seu objetivo",
  LocaleKey.noDataFound: "Ops! Nenhum Dado Encontrado.",
  LocaleKey.contnue: "Continuar",
  LocaleKey.subscribedSuccessfully: "Inscrito com sucesso",
  LocaleKey.thereAreNoUpgradesAtThisTime: "Não há atualizações no momento",
  LocaleKey.pending: "Pendente",
  LocaleKey.noPackageFound:
      "Pacote não encontrado. Tente novamente mais tarde!",
  LocaleKey.checkYourInternetConnection:
      "Verifique sua conexão com a internet.",
  LocaleKey.noInternet: "Sem Internet",
  LocaleKey.checkUpdateDesc:
      "Gostaria de verificar se há atualizações disponíveis na Play Store?",
  LocaleKey.check: "Verificar",
  LocaleKey.stepIntoWellness: "Entre no bem-estar",
  LocaleKey.trackStepsBurnCaloriesLiveHealthier:
      "Rastreie passos, queime calorias, viva mais saudável!",
  LocaleKey.exit: "Sair",
  LocaleKey.refresh: "Atualizar",
  LocaleKey.billedEvery: "Cobrado a Cada",
  LocaleKey.targetCaloriesToBurn: "Calorias Alvo Para Queimar",
  LocaleKey.hurrahYouHitTheTargetCaloriesBurn:
      "Hurra! 🎊🎉 Você atingiu sua meta de queima de calorias!",
  LocaleKey.routeSaved: "Rota Salva",
  LocaleKey.saveYourRoute: "Salve Sua Rota",
  LocaleKey.routeName: "Nome da Rota",
  LocaleKey.saveRoutes: "Salvar Rotas",
  LocaleKey.unknown: "Desconhecido",
  LocaleKey.route: "Rota",
};
